### PR TITLE
It is my modest attempt to improve your functions

### PR DESCRIPTION
**Pull request by axsano**
I've included some features of Julia, such as:

- const
- variable types
- loop break

In my tests, the function runs two times faster than the original.

### CODE REVIEW

**Comment by marianoarnaiz** [comment]
Hi Alex!
Thank you so much!
I will study the changes you made to the code!
Very helpfull!!!!!

**Review by marianoarnaiz — APPROVED** [review]

**Review by marianoarnaiz — COMMENTED** [review]
Looks great man! I will try to run it this way

**Comment by marianoarnaiz** [comment]
Hi Alex. I have uploaded the missing file, if you care to test the updated code with it! Thanks again!

**Comment by marianoarnaiz** [comment]
Hi Alex. I tested, but I am reviewing the changes. The Rays are not Bending... they just stay linear... I don't know what happens

**Comment by axsano** [comment]
Hello Mariano,

My bad, but let me know, is the previous version is working? I mean, the
version with my first pull request?

I will try again and look for what I did wrong.

Sincerely.

**Comment by marianoarnaiz** [comment]
Hey man!
The first version is fantastic... it has helped me a lot!. 
Thanks for helping man!

**Comment by axsano** [comment]
Nice,

But did you measure how much the code improved in execution speed?

If it is possible could you update the repository with the version that is
working well?

Thanks.

**Comment by marianoarnaiz** [comment]
Yeah man. Let me get home and I will!

**Comment by marianoarnaiz** [comment]
Hi Alex. 
The last version that worked well is here:
https://github.com/marianoarnaiz/JULIA2

With all the updates. I wonder if you would like to help me finish this part of the code and you can be part of the up comming publication. Please email me if you are interested (marianoarnaiz@gmail.com)

Thanks again for the help

**Pull request merged**
